run:
  go: "1.23"
  tests: false

linters:
  disable-all: true
  enable:
    - bodyclose
    - errcheck
    - goconst
    - gocritic
    - gofmt
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - revive

linters-settings:
  goimports:
    local-prefixes: viper

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck

    - path: \.resolvers\.go
      linters:
        - lll

    - linters:
        - lll
      source: "^//go:generate "
