x-common-base: &common-base
  restart: always
  networks:
    - backend

services:
  asynqmon:
    <<: *common-base
    profiles: ["asynq"]
    image: hibiken/asynqmon:${ASYNQMON_VERSION:-latest}
    platform: linux/x86_64
    ports:
      - 7080:8080
    environment:
      - REDIS_URL=redis://redis:6379/0
