volumes:
  prometheus-storage: {}
  grafana-storage: {}
  alloy-storage: {}

networks:
  monitoring: {}

x-common: &common
  env_file:
    - path: ../.env
      required: false
  profiles:
    - tools
  networks:
    - monitoring

services:
  prometheus:
    << : [ *common ]
    image: prom/prometheus:v3.0.0
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./monitoring:/etc/prometheus
      - prometheus-storage:/prometheus
    command:
      - '--config.file=/etc/prometheus/prom.config.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=24h'

  grafana:
    << : [ *common ]
    image: grafana/grafana:11.4.0
    restart: always
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana

  alloy:
    << : [ *common ]
    image: grafana/alloy:v1.5.0
    restart: always
    ports:
      - 12345:12345
    volumes:
      - ./monitoring/config.alloy:/etc/alloy/config.alloy
      - alloy-storage:/var/lib/alloy/data
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy/data
      - /etc/alloy/config.alloy
