 services:
  jupiter:
    image: cr.yandex/crp53e20ig6qqj16t4k5/jupiter:${IMAGE_TAG:-develop}
    build:
      context: ../.
      dockerfile: dockers/Dockerfile.jupiter
      network: host
      args:
        DOCKER_BUILDKIT: 1
    restart: always
    network_mode: host
    env_file:
      - path: ../.env
        required: false
