debug: false

logger:
  level: info

ydb:
  dsn: grpcs://ydb.serverless.yandexcloud.net:2135/?database=/ru-central1/b1gqfuj7kccoqo8l6vb5/etn9p8jg97l7kc7inv4u
  access_token_credentials:

fasthttp:
  client:
    max_conns_per_host: 1024
    max_conn_duration: 1m
    max_conn_wait_timeout: 5s
    read_timeout: 5s
    write_timeout: 5s

jupyter:
  # token api
  token:
    host: https://tokens.jup.ag/token

  # price api
  price:
    host: https://api.jup.ag/price/v2

  # quote api with round-robin LB
  quote:
    hosts:
      - https://quote-api.jup.ag/v6/quote
      - https://public.jupiterapi.com/quote

instruments:
  # available instruments
  pool:
    - ticker: sol
      address: So11111111111111111111111111111111111111112
      decimals: 9

    - ticker: usdt
      address: Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB
      decimals: 6

    - ticker: usdc
      address: EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v
      decimals: 6

    - ticker: jup
      address: JUPyiwrYJFskUPiHa7hkeR8VUtAeFoSYbKedZNsDvCN
      decimals: 6

    - ticker: jlp
      address: 27G8MtK7VtTcCHkpASjSDdkWWYfoqT6ggEuKidVJidD4
      decimals: 6

    - ticker: bonk
      address: DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263
      decimals: 5

routes:
  # amount range in route pool for each base_ccy
  range: [0, 2]

  # using this step, decimals = 1000
  step: 1

  base_ccy:
    # SOL
    - So11111111111111111111111111111111111111112

    # USDT
    - Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB

    # USDC
    - EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v

server:
  # check quotes concurrency
  concurrency: 3

  # block producer interval
  ticker: 10s

  # timeout deadline for group task
  deadline: 10s
