debug: false

logger:
  level: info

ydb:
  dsn: grpcs://ydb.serverless.yandexcloud.net:2135/?database=/ru-central1/b1gcm11knnnopur9fil6/etn4hff7q981ib0o7mnl
  access_token_credentials:

fasthttp:
  client:
    max_conns_per_host: 1024
    max_conn_duration: 1m
    max_conn_wait_timeout: 5s
    read_timeout: 5s
    write_timeout: 5s

jupyter:
  # token api
  token:
    host: https://tokens.jup.ag/tokens

  # price api
  price:
    host: https://api.jup.ag/price/v2

  # quote api with round-robin LB
  quote:
    hosts:
      - https://quote-api.jup.ag/v6/quote
      - https://public.jupiterapi.com/quote

instruments:
  # available instruments
  pool:
    - ticker: usdc
      address: EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v
      decimals: 6
      tags: [base, route, swap]

    - ticker: usdt
      address: Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB
      decimals: 6
      tags: [base, route, swap]

    - ticker: usds
      address: USDSwr9ApdHk5bvJKMjzff41FfuX8bSxdKcR81vTwcA
      decimals: 6
      tags: [route, swap]

    - ticker: sol
      address: So11111111111111111111111111111111111111112
      decimals: 9
      tags: [route, swap]

    - ticker: jup
      address: JUPyiwrYJFskUPiHa7hkeR8VUtAeFoSYbKedZNsDvCN
      decimals: 6
      tags: [route, swap]

    - ticker: jlp
      address: 27G8MtK7VtTcCHkpASjSDdkWWYfoqT6ggEuKidVJidD4
      decimals: 6
      tags: [route, swap]

    - ticker: bonk
      address: DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263
      decimals: 5
      tags: [route, swap]

    - ticker: me
      address: MEFNBXixkEbait3xn9bkm8WsJzXtVsaJEn4c8Sam21u
      decimals: 6
      tags: [swap]

    - ticker: jito
      address: J1toso1uCk3RLmjorhTtrVwY9HJ7X8V9yYac6Y7kGCPn
      decimals: 9
      tags: [swap]

    - ticker: wbtc
      address: 3NZ9JMVBmGAqocybic2c7LQCJScmgsAZ6vQqTDzcqmJh
      decimals: 8
      tags: [swap]

    - ticker: eth
      address: 7vfCXTUXx5WJV5JADk17DUJ4ksgau7utNKj4b963voxs
      decimals: 8
      tags: [swap]

    - ticker: popcat
      address: 7GCihgDB8fe6KNjn2MYtkzZcRjQy3t9GHdC8uHYmW2hr
      decimals: 9
      tags: [swap]

    - ticker: ray
      address: 4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R
      decimals: 6
      tags: [swap]

routes:
  # amount range in route pool for each base intruments
  range: [1, 5]

  # using this step, decimals = 1000
  step: 1

server:
  # check quotes concurrency
  concurrency: 5

  # block producer interval
  ticker: 10s

  # timeout deadline for group task
  deadline: 10s
