debug: false

logger:
  level: info

ydb:
  dsn: grpcs://ydb.serverless.yandexcloud.net:2135/?database=/ru-central1/b1gcm11knnnopur9fil6/etn4hff7q981ib0o7mnl
  access_token_credentials:

fasthttp:
  client:
    max_conns_per_host: 1024
    max_conn_duration: 1m
    max_conn_wait_timeout: 5s
    read_timeout: 5s
    write_timeout: 5s

jupiter:
  # token api
  token:
    host: https://tokens.jup.ag/tokens

  # price api
  price:
    host: https://api.jup.ag/price/v2

  # quote api with round-robin LB
  quote:
    hosts:
      - https://quote-api.jup.ag/v6/quote
      - https://public.jupiterapi.com/quote

instruments:
  # tokens loader
  loader:
    skip:
      daily_volume: 1_000_000

  # available instruments
  pool:
    # usdc
    - address: EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v
      tags: [base, route]

    # usdt
    # - address: Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB
    #   tags: [base, route]

    # usds
    # - address: USDSwr9ApdHk5bvJKMjzff41FfuX8bSxdKcR81vTwcA
    #   tags: [route]

    # wsol
    # - address: So11111111111111111111111111111111111111112
    #   tags: [route]

    # jup
    - address: JUPyiwrYJFskUPiHa7hkeR8VUtAeFoSYbKedZNsDvCN
      tags: [route]

    # jlp
    - address: 27G8MtK7VtTcCHkpASjSDdkWWYfoqT6ggEuKidVJidD4
      tags: [route]

    # bonk
    - address: DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263
      tags: [route]

    # jito
    # - address: J1toso1uCk3RLmjorhTtrVwY9HJ7X8V9yYac6Y7kGCPn
    #   tags: [route]

    # wbtc
    # - address: 3NZ9JMVBmGAqocybic2c7LQCJScmgsAZ6vQqTDzcqmJh
    #   tags: [route]

    # eth
    # - address: 7vfCXTUXx5WJV5JADk17DUJ4ksgau7utNKj4b963voxs
    #   tags: [route]

    # ray
    # - address: 4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R
    #   tags: [route]

routes:
  # amount range in route pool for each base intruments
  range: [1, 5]

  # using this step, decimals = 1000
  step: 1

prices:
  loader:
    # split requests to jupiter api
    chunk_size: 100

server:
  # check quotes concurrency
  concurrency: 5

  # block producer interval
  ticker: 10s

  # timeout deadline for group task
  deadline: 10s
