debug: false

logger:
  level: info

monitoring:
  sentry: {}
  metrics: {}

http:
  bind: 0.0.0.0:8080

ydb:
  dsn: grpcs://ydb.serverless.yandexcloud.net:2135/?database=/ru-central1/b1gcm11knnnopur9fil6/etn4hff7q981ib0o7mnl
  access_token_credentials:

fasthttp:
  client:
    host:
      max_conns_per_host: 1024
      max_conn_duration: 5m
      max_conn_wait_timeout: 5s
      read_timeout: 1s
      read_buffer_size: 4096
      write_timeout: 1s
      write_buffer_size: 4096

jupiter:
  # token api
  token:
    hosts:
      - https://tokens.jup.ag/tokens

    # take tokens with selected tags from jupiter
    tags:
      - verified

  # price api
  price:
    hosts:
      - https://api.jup.ag/price/v2

  # quote api
  quote:
    only_direct_routes: true
    restrict_intermediate_tokens: true

    # with round-robin LB
    hosts:
      - https://quote-api.jup.ag/v6/quote
      - https://public.jupiterapi.com/quote

server:
  # check quotes concurrency
  concurrency: 5

  # block producer interval
  ticker: 10s

  # timeout deadline for group task
  deadline: 10s

routes:
  # amount range in route pool for each base intruments
  range: [1, 2]

  # using this step, decimals = 1000
  step: 1

prices:
  loader:
    # split requests to jupiter api
    chunk_size: 99

instruments:
  # tokens loader
  loader:
    skip:
      daily_volume: 1_000_000

  # available instruments
  pool:
    # wsol
    - address: So11111111111111111111111111111111111111112
      tags: [base, route]

    # usdc
    - address: EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v
      tags: [base, route]

    # usdt
    # - address: Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB
    #   tags: [route]

    # me
    - address: MEFNBXixkEbait3xn9bkm8WsJzXtVsaJEn4c8Sam21u
      tags: [route]

    # jup
    - address: JUPyiwrYJFskUPiHa7hkeR8VUtAeFoSYbKedZNsDvCN
      tags: [route]

    # jlp
    - address: 27G8MtK7VtTcCHkpASjSDdkWWYfoqT6ggEuKidVJidD4
      tags: [route]

    # bonk
    - address: DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263
      tags: [route]

    # jito
    - address: J1toso1uCk3RLmjorhTtrVwY9HJ7X8V9yYac6Y7kGCPn
      tags: [route]

    # ray
    - address: 4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R
      tags: [route]

    # usds
    # - address: USDSwr9ApdHk5bvJKMjzff41FfuX8bSxdKcR81vTwcA
    #   tags: [route]

    # wbtc
    # - address: 3NZ9JMVBmGAqocybic2c7LQCJScmgsAZ6vQqTDzcqmJh
    #   tags: [route]

    # eth
    # - address: 7vfCXTUXx5WJV5JADk17DUJ4ksgau7utNKj4b963voxs
    #   tags: [route]
