server:
  concurrency: 500
  ticker: 10s
  deadline: 5s

jupiter:
  quote:
    hosts:
      - http://jupiter:8080/quote

routes:
  range: [1, 10]
  step: 1

instruments:
  pool:
    - address: So11111111111111111111111111111111111111112
      tags: [base, route]
    - address: DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263
      tags: [route]
    - address: 7vfCXTUXx5WJV5JADk17DUJ4ksgau7utNKj4b963voxs
      tags: [route]
    - address: 3NZ9JMVBmGAqocybic2c7LQCJScmgsAZ6vQqTDzcqmJh
      tags: [route]
    - address: JUPyiwrYJFskUPiHa7hkeR8VUtAeFoSYbKedZNsDvCN
      tags: [route]
    - address: EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v
      tags: [route]
    - address: 27G8MtK7VtTcCHkpASjSDdkWWYfoqT6ggEuKidVJidD4
      tags: [route]
