name: build

on:
  push:
    branches:
      - "main"
      - "develop"
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1
  COMPOSE_PROFILES: tools

  image_path: cr.yandex/crp53e20ig6qqj16t4k5
  image_tag: develop

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-golang-deps

      - uses: docker/setup-buildx-action@v3

      - uses: yc-actions/yc-cr-login@v2
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

      - uses: docker/build-push-action@v6
        id: build-docker
        with:
          context: .
          file: ./dockers/Dockerfile.app
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          provenance: false
          tags: |
            ${{ env.image_path }}/app:${{ env.image_tag }}
